version: '3'
name: bullet

services: 
  postgres: 
      image: postgres
      restart: always
      ports: 
        - '5432:5432'
      environment: 
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: bullet
      volumes:
        - /var/lib/postgresql/data